global using Civil_Registration_System_Platform.Models; 
global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using Civil_Registration_System_Platform.ViewModel;

global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore;

global using Civil_Registration_System_Platform.Account.AccountViewModel;


global using Civil_Registration_System_Platform.Account.AccountRepository;
global using Civil_Registration_System_Platform.Account.AccountServices;
global using Civil_Registration_System_Platform.GlobalServices.GlobalClass;
global using Civil_Registration_System_Platform.GlobalServices.GlobalInterface;