// <auto-generated />
using System;
using Civil_Registration_System_Platform.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Civil_Registration_System_Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260505134834_SeedServicesTypeHelperData")]
    partial class SeedServicesTypeHelperData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Civil_Registration_System_Platform.Models.Application", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationId"));

                    b.Property<string>("ApplicationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ApplicationType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("OfficeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ServiceType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ApplicationId");

                    b.HasIndex("ApplicationNumber")
                        .IsUnique();

                    b.HasIndex("OfficeId");

                    b.HasIndex("ReviewedById");

                    b.HasIndex("UserAccountId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("Civil_Registration_System_Platform.Models.ApplicationDocuments", b =>
                {
                    b.Property<int>("ApplicationDocumentsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationDocumentsId"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("DocumentPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("UserAccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApplicationDocumentsId");

                    b.HasIndex("ApplicationId");

                    b.ToTable("ApplicationDocuments");
                });

            modelBuilder.Entity("Civil_Registration_System_Platform.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ScheduledById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserAccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AppointmentId");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("ScheduledById");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Civil_Registration_System_Platform.Models.Governorate", b =>
                {
                    b.Property<int>("GovernorateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GovernorateId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("GovernorateId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Governorates");

                    b.HasData(
                        new
                        {
                            GovernorateId = 1,
                            Code = "C",
                            IsActive = true,
                            Name = "القاهرة"
                        },
                        new
                        {
                            GovernorateId = 2,
                            Code = "GZ",
                            IsActive = true,
                            Name = "الجيزة"
                        },
                        new
                        {
                            GovernorateId = 3,
                            Code = "ALX",
                            IsActive = true,
                            Name = "الإسكندرية"
                        },
                        new
                        {
                            GovernorateId = 4,
                            Code = "DK",
                            IsActive = true,
                            Name = "الدقهلية"
                        },
                        new
                        {
                            GovernorateId = 5,
                            Code = "BA",
                            IsActive = true,
                            Name = "البحر الأحمر"
                        },
                        new
                        {
                            GovernorateId = 6,
                            Code = "BH",
                            IsActive = true,
                            Name = "البحيرة"
                        },
                        new
                        {
                            GovernorateId = 7,
                            Code = "FYM",
                            IsActive = true,
                            Name = "الفيوم"
                        },
                        new
                        {
                            GovernorateId = 8,
                            Code = "GH",
                            IsActive = true,
                            Name = "الغربية"
                        },
                        new
                        {
                            GovernorateId = 9,
                            Code = "IS",
                            IsActive = true,
                            Name = "الإسماعيلية"
                        },
                        new
                        {
                            GovernorateId = 10,
                            Code = "MN",
                            IsActive = true,
                            Name = "المنوفية"
                        },
                        new
                        {
                            GovernorateId = 11,
                            Code = "MNIA",
                            IsActive = true,
                            Name = "المنيا"
                        },
                        new
                        {
                            GovernorateId = 12,
                            Code = "KB",
                            IsActive = true,
                            Name = "القليوبية"
                        },
                        new
                        {
                            GovernorateId = 13,
                            Code = "WAD",
                            IsActive = true,
                            Name = "الوادي الجديد"
                        },
                        new
                        {
                            GovernorateId = 14,
                            Code = "SUZ",
                            IsActive = true,
                            Name = "السويس"
                        },
                        new
                        {
                            GovernorateId = 15,
                            Code = "ASN",
                            IsActive = true,
                            Name = "اسوان"
                        },
                        new
                        {
                            GovernorateId = 16,
                            Code = "AST",
                            IsActive = true,
                            Name = "اسيوط"
                        },
                        new
                        {
                            GovernorateId = 17,
                            Code = "BNS",
                            IsActive = true,
                            Name = "بني سويف"
                        },
                        new
                        {
                            GovernorateId = 18,
                            Code = "PTS",
                            IsActive = true,
                            Name = "بورسعيد"
                        },
                        new
                        {
                            GovernorateId = 19,
                            Code = "DT",
                            IsActive = true,
                            Name = "دمياط"
                        },
                        new
                        {
                            GovernorateId = 20,
                            Code = "SHR",
                            IsActive = true,
                            Name = "الشرقية"
                        },
                        new
                        {
                            GovernorateId = 21,
                            Code = "JS",
                            IsActive = true,
                            Name = "جنوب سيناء"
                        },
                        new
                        {
                            GovernorateId = 22,
                            Code = "KFS",
                            IsActive = true,
                            Name = "كفر الشيخ"
                        },
                        new
                        {
                            GovernorateId = 23,
                            Code = "MT",
                            IsActive = true,
                            Name = "مطروح"
                        },
                        new
                        {
                            GovernorateId = 24,
                            Code = "LUX",
                            IsActive = true,
                            Name = "الأقصر"
                        },
                        new
                        {
                            GovernorateId = 25,
                            Code = "KN",
                            IsActive = true,
                            Name = "قنا"
                        },
                        new
                        {
                            GovernorateId = 26,
                            Code = "NS",
                            IsActive = true,
                            Name = "شمال سيناء"
                        },
                        new
                        {
                            GovernorateId = 27,
                            Code = "SHG",
                            IsActive = true,
                            Name = "سوهاج"
                        });
                });

            modelBuilder.Entity("Civil_Registration_System_Platform.Models.Office", b =>
                {
                    b.Property<int>("OfficeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfficeId"));

                    b.Property<int>("GovernorateId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("OfficeId");

                    b.HasIndex("GovernorateId");

                    b.ToTable("Offices");

                    b.HasData(
                        new
                        {
                            OfficeId = 1,
                            GovernorateId = 1,
                            IsActive = true,
                            Name = "مركز النزهة",
                            Phone = "01000000001"
                        },
                        new
                        {
                            OfficeId = 2,
                            GovernorateId = 1,
                            IsActive = true,
                            Name = "مركز مدينة نصر",
                            Phone = "01000000002"
                        },
                        new
                        {
                            OfficeId = 3,
                            GovernorateId = 1,
                            IsActive = true,
                            Name = "مركز عين شمس",
                            Phone = "01000000003"
                        },
                        new
                        {
                            OfficeId = 4,
                            GovernorateId = 1,
                            IsActive = true,
                            Name = "مركز حلوان",
                            Phone = "01000000004"
                        },
                        new
                        {
                            OfficeId = 5,
                            GovernorateId = 1,
                            IsActive = true,
                            Name = "مركز المعادي",
                            Phone = "01000000005"
                        },
                        new
                        {
                            OfficeId = 6,
                            GovernorateId = 1,
                            IsActive = true,
                            Name = "مركز شبرا",
                            Phone = "01000000006"
                        },
                        new
                        {
                            OfficeId = 7,
                            GovernorateId = 1,
                            IsActive = true,
                            Name = "مركز الزيتون",
                            Phone = "01000000007"
                        },
                        new
                        {
                            OfficeId = 8,
                            GovernorateId = 1,
                            IsActive = true,
                            Name = "مركز التبين",
                            Phone = "01000000008"
                        },
                        new
                        {
                            OfficeId = 9,
                            GovernorateId = 2,
                            IsActive = true,
                            Name = "مركز الجيزة",
                            Phone = "01000000009"
                        },
                        new
                        {
                            OfficeId = 10,
                            GovernorateId = 2,
                            IsActive = true,
                            Name = "مركز الشيخ زايد",
                            Phone = "01000000010"
                        },
                        new
                        {
                            OfficeId = 11,
                            GovernorateId = 2,
                            IsActive = true,
                            Name = "مركز أكتوبر",
                            Phone = "01000000011"
                        },
                        new
                        {
                            OfficeId = 12,
                            GovernorateId = 2,
                            IsActive = true,
                            Name = "مركز الحوامدية",
                            Phone = "01000000012"
                        },
                        new
                        {
                            OfficeId = 13,
                            GovernorateId = 2,
                            IsActive = true,
                            Name = "مركز البدرشين",
                            Phone = "01000000013"
                        },
                        new
                        {
                            OfficeId = 14,
                            GovernorateId = 2,
                            IsActive = true,
                            Name = "مركز العياط",
                            Phone = "01000000014"
                        },
                        new
                        {
                            OfficeId = 15,
                            GovernorateId = 2,
                            IsActive = true,
                            Name = "مركز الصف",
                            Phone = "01000000015"
                        },
                        new
                        {
                            OfficeId = 16,
                            GovernorateId = 2,
                            IsActive = true,
                            Name = "مركز أطفيح",
                            Phone = "01000000016"
                        },
                        new
                        {
                            OfficeId = 17,
                            GovernorateId = 3,
                            IsActive = true,
                            Name = "مركز المنتزه",
                            Phone = "01000000017"
                        },
                        new
                        {
                            OfficeId = 18,
                            GovernorateId = 3,
                            IsActive = true,
                            Name = "مركز العجمي",
                            Phone = "01000000018"
                        },
                        new
                        {
                            OfficeId = 19,
                            GovernorateId = 3,
                            IsActive = true,
                            Name = "مركز برج العرب",
                            Phone = "01000000019"
                        },
                        new
                        {
                            OfficeId = 20,
                            GovernorateId = 3,
                            IsActive = true,
                            Name = "مركز الدخيلة",
                            Phone = "01000000020"
                        },
                        new
                        {
                            OfficeId = 21,
                            GovernorateId = 3,
                            IsActive = true,
                            Name = "مركز سيدي بشر",
                            Phone = "01000000021"
                        },
                        new
                        {
                            OfficeId = 22,
                            GovernorateId = 4,
                            IsActive = true,
                            Name = "مركز المنصورة",
                            Phone = "01000000022"
                        },
                        new
                        {
                            OfficeId = 23,
                            GovernorateId = 4,
                            IsActive = true,
                            Name = "مركز طلخا",
                            Phone = "01000000023"
                        },
                        new
                        {
                            OfficeId = 24,
                            GovernorateId = 4,
                            IsActive = true,
                            Name = "مركز دكرنس",
                            Phone = "01000000024"
                        },
                        new
                        {
                            OfficeId = 25,
                            GovernorateId = 4,
                            IsActive = true,
                            Name = "مركز ميت غمر",
                            Phone = "01000000025"
                        },
                        new
                        {
                            OfficeId = 26,
                            GovernorateId = 4,
                            IsActive = true,
                            Name = "مركز أجا",
                            Phone = "01000000026"
                        },
                        new
                        {
                            OfficeId = 27,
                            GovernorateId = 4,
                            IsActive = true,
                            Name = "مركز المنزلة",
                            Phone = "01000000027"
                        },
                        new
                        {
                            OfficeId = 28,
                            GovernorateId = 4,
                            IsActive = true,
                            Name = "مركز بلقاس",
                            Phone = "01000000028"
                        },
                        new
                        {
                            OfficeId = 29,
                            GovernorateId = 4,
                            IsActive = true,
                            Name = "مركز شربين",
                            Phone = "01000000029"
                        },
                        new
                        {
                            OfficeId = 30,
                            GovernorateId = 4,
                            IsActive = true,
                            Name = "مركز السنبلاوين",
                            Phone = "01000000030"
                        },
                        new
                        {
                            OfficeId = 31,
                            GovernorateId = 4,
                            IsActive = true,
                            Name = "مركز تمي الأمديد",
                            Phone = "01000000031"
                        },
                        new
                        {
                            OfficeId = 32,
                            GovernorateId = 5,
                            IsActive = true,
                            Name = "مركز الغردقة",
                            Phone = "01000000032"
                        },
                        new
                        {
                            OfficeId = 33,
                            GovernorateId = 5,
                            IsActive = true,
                            Name = "مركز سفاجا",
                            Phone = "01000000033"
                        },
                        new
                        {
                            OfficeId = 34,
                            GovernorateId = 5,
                            IsActive = true,
                            Name = "مركز القصير",
                            Phone = "01000000034"
                        },
                        new
                        {
                            OfficeId = 35,
                            GovernorateId = 5,
                            IsActive = true,
                            Name = "مركز مرسى علم",
                            Phone = "01000000035"
                        },
                        new
                        {
                            OfficeId = 36,
                            GovernorateId = 5,
                            IsActive = true,
                            Name = "مركز رأس غارب",
                            Phone = "01000000036"
                        },
                        new
                        {
                            OfficeId = 37,
                            GovernorateId = 6,
                            IsActive = true,
                            Name = "مركز دمنهور",
                            Phone = "01000000037"
                        },
                        new
                        {
                            OfficeId = 38,
                            GovernorateId = 6,
                            IsActive = true,
                            Name = "مركز كفر الدوار",
                            Phone = "01000000038"
                        },
                        new
                        {
                            OfficeId = 39,
                            GovernorateId = 6,
                            IsActive = true,
                            Name = "مركز الرحمانية",
                            Phone = "01000000039"
                        },
                        new
                        {
                            OfficeId = 40,
                            GovernorateId = 6,
                            IsActive = true,
                            Name = "مركز إيتاي البارود",
                            Phone = "01000000040"
                        },
                        new
                        {
                            OfficeId = 41,
                            GovernorateId = 6,
                            IsActive = true,
                            Name = "مركز أبو حمص",
                            Phone = "01000000041"
                        },
                        new
                        {
                            OfficeId = 42,
                            GovernorateId = 6,
                            IsActive = true,
                            Name = "مركز المحمودية",
                            Phone = "01000000042"
                        },
                        new
                        {
                            OfficeId = 43,
                            GovernorateId = 6,
                            IsActive = true,
                            Name = "مركز رشيد",
                            Phone = "01000000043"
                        },
                        new
                        {
                            OfficeId = 44,
                            GovernorateId = 6,
                            IsActive = true,
                            Name = "مركز شبراخيت",
                            Phone = "01000000044"
                        },
                        new
                        {
                            OfficeId = 45,
                            GovernorateId = 6,
                            IsActive = true,
                            Name = "مركز وادي النطرون",
                            Phone = "01000000045"
                        },
                        new
                        {
                            OfficeId = 46,
                            GovernorateId = 7,
                            IsActive = true,
                            Name = "مركز الفيوم",
                            Phone = "01000000046"
                        },
                        new
                        {
                            OfficeId = 47,
                            GovernorateId = 7,
                            IsActive = true,
                            Name = "مركز سنورس",
                            Phone = "01000000047"
                        },
                        new
                        {
                            OfficeId = 48,
                            GovernorateId = 7,
                            IsActive = true,
                            Name = "مركز إطسا",
                            Phone = "01000000048"
                        },
                        new
                        {
                            OfficeId = 49,
                            GovernorateId = 7,
                            IsActive = true,
                            Name = "مركز طامية",
                            Phone = "01000000049"
                        },
                        new
                        {
                            OfficeId = 50,
                            GovernorateId = 7,
                            IsActive = true,
                            Name = "مركز يوسف الصديق",
                            Phone = "01000000050"
                        },
                        new
                        {
                            OfficeId = 51,
                            GovernorateId = 8,
                            IsActive = true,
                            Name = "مركز طنطا",
                            Phone = "01000000051"
                        },
                        new
                        {
                            OfficeId = 52,
                            GovernorateId = 8,
                            IsActive = true,
                            Name = "مركز المحلة الكبرى",
                            Phone = "01000000052"
                        },
                        new
                        {
                            OfficeId = 53,
                            GovernorateId = 8,
                            IsActive = true,
                            Name = "مركز زفتى",
                            Phone = "01000000053"
                        },
                        new
                        {
                            OfficeId = 54,
                            GovernorateId = 8,
                            IsActive = true,
                            Name = "مركز السنطة",
                            Phone = "01000000054"
                        },
                        new
                        {
                            OfficeId = 55,
                            GovernorateId = 8,
                            IsActive = true,
                            Name = "مركز قطور",
                            Phone = "01000000055"
                        },
                        new
                        {
                            OfficeId = 56,
                            GovernorateId = 8,
                            IsActive = true,
                            Name = "مركز بسيون",
                            Phone = "01000000056"
                        },
                        new
                        {
                            OfficeId = 57,
                            GovernorateId = 8,
                            IsActive = true,
                            Name = "مركز كفر الزيات",
                            Phone = "01000000057"
                        },
                        new
                        {
                            OfficeId = 58,
                            GovernorateId = 9,
                            IsActive = true,
                            Name = "مركز الإسماعيلية",
                            Phone = "01000000058"
                        },
                        new
                        {
                            OfficeId = 59,
                            GovernorateId = 9,
                            IsActive = true,
                            Name = "مركز فايد",
                            Phone = "01000000059"
                        },
                        new
                        {
                            OfficeId = 60,
                            GovernorateId = 9,
                            IsActive = true,
                            Name = "مركز القنطرة شرق",
                            Phone = "01000000060"
                        },
                        new
                        {
                            OfficeId = 61,
                            GovernorateId = 9,
                            IsActive = true,
                            Name = "مركز القنطرة غرب",
                            Phone = "01000000061"
                        },
                        new
                        {
                            OfficeId = 62,
                            GovernorateId = 9,
                            IsActive = true,
                            Name = "مركز أبو صوير",
                            Phone = "01000000062"
                        },
                        new
                        {
                            OfficeId = 63,
                            GovernorateId = 10,
                            IsActive = true,
                            Name = "مركز شبين الكوم",
                            Phone = "01000000063"
                        },
                        new
                        {
                            OfficeId = 64,
                            GovernorateId = 10,
                            IsActive = true,
                            Name = "مركز منوف",
                            Phone = "01000000064"
                        },
                        new
                        {
                            OfficeId = 65,
                            GovernorateId = 10,
                            IsActive = true,
                            Name = "مركز السادات",
                            Phone = "01000000065"
                        },
                        new
                        {
                            OfficeId = 66,
                            GovernorateId = 10,
                            IsActive = true,
                            Name = "مركز تلا",
                            Phone = "01000000066"
                        },
                        new
                        {
                            OfficeId = 67,
                            GovernorateId = 10,
                            IsActive = true,
                            Name = "مركز قويسنا",
                            Phone = "01000000067"
                        },
                        new
                        {
                            OfficeId = 68,
                            GovernorateId = 10,
                            IsActive = true,
                            Name = "مركز بركة السبع",
                            Phone = "01000000068"
                        },
                        new
                        {
                            OfficeId = 69,
                            GovernorateId = 10,
                            IsActive = true,
                            Name = "مركز أشمون",
                            Phone = "01000000069"
                        },
                        new
                        {
                            OfficeId = 70,
                            GovernorateId = 10,
                            IsActive = true,
                            Name = "مركز الشهداء",
                            Phone = "01000000070"
                        },
                        new
                        {
                            OfficeId = 71,
                            GovernorateId = 11,
                            IsActive = true,
                            Name = "مركز المنيا",
                            Phone = "01000000071"
                        },
                        new
                        {
                            OfficeId = 72,
                            GovernorateId = 11,
                            IsActive = true,
                            Name = "مركز أبو قرقاص",
                            Phone = "01000000072"
                        },
                        new
                        {
                            OfficeId = 73,
                            GovernorateId = 11,
                            IsActive = true,
                            Name = "مركز بني مزار",
                            Phone = "01000000073"
                        },
                        new
                        {
                            OfficeId = 74,
                            GovernorateId = 11,
                            IsActive = true,
                            Name = "مركز مطاي",
                            Phone = "01000000074"
                        },
                        new
                        {
                            OfficeId = 75,
                            GovernorateId = 11,
                            IsActive = true,
                            Name = "مركز ملوي",
                            Phone = "01000000075"
                        },
                        new
                        {
                            OfficeId = 76,
                            GovernorateId = 11,
                            IsActive = true,
                            Name = "مركز سمالوط",
                            Phone = "01000000076"
                        },
                        new
                        {
                            OfficeId = 77,
                            GovernorateId = 11,
                            IsActive = true,
                            Name = "مركز العدوة",
                            Phone = "01000000077"
                        },
                        new
                        {
                            OfficeId = 78,
                            GovernorateId = 11,
                            IsActive = true,
                            Name = "مركز دير مواس",
                            Phone = "01000000078"
                        },
                        new
                        {
                            OfficeId = 79,
                            GovernorateId = 12,
                            IsActive = true,
                            Name = "مركز بنها",
                            Phone = "01000000079"
                        },
                        new
                        {
                            OfficeId = 80,
                            GovernorateId = 12,
                            IsActive = true,
                            Name = "مركز شبين القناطر",
                            Phone = "01000000080"
                        },
                        new
                        {
                            OfficeId = 81,
                            GovernorateId = 12,
                            IsActive = true,
                            Name = "مركز قليوب",
                            Phone = "01000000081"
                        },
                        new
                        {
                            OfficeId = 82,
                            GovernorateId = 12,
                            IsActive = true,
                            Name = "مركز القناطر الخيرية",
                            Phone = "01000000082"
                        },
                        new
                        {
                            OfficeId = 83,
                            GovernorateId = 12,
                            IsActive = true,
                            Name = "مركز طوخ",
                            Phone = "01000000083"
                        },
                        new
                        {
                            OfficeId = 84,
                            GovernorateId = 12,
                            IsActive = true,
                            Name = "مركز الخانكة",
                            Phone = "01000000084"
                        },
                        new
                        {
                            OfficeId = 85,
                            GovernorateId = 12,
                            IsActive = true,
                            Name = "مركز كفر شكر",
                            Phone = "01000000085"
                        },
                        new
                        {
                            OfficeId = 86,
                            GovernorateId = 13,
                            IsActive = true,
                            Name = "مركز الخارجة",
                            Phone = "01000000086"
                        },
                        new
                        {
                            OfficeId = 87,
                            GovernorateId = 13,
                            IsActive = true,
                            Name = "مركز الداخلة",
                            Phone = "01000000087"
                        },
                        new
                        {
                            OfficeId = 88,
                            GovernorateId = 13,
                            IsActive = true,
                            Name = "مركز الفرافرة",
                            Phone = "01000000088"
                        },
                        new
                        {
                            OfficeId = 89,
                            GovernorateId = 13,
                            IsActive = true,
                            Name = "مركز بلاط",
                            Phone = "01000000089"
                        },
                        new
                        {
                            OfficeId = 90,
                            GovernorateId = 14,
                            IsActive = true,
                            Name = "مركز السويس",
                            Phone = "01000000090"
                        },
                        new
                        {
                            OfficeId = 91,
                            GovernorateId = 14,
                            IsActive = true,
                            Name = "مركز عتاقة",
                            Phone = "01000000091"
                        },
                        new
                        {
                            OfficeId = 92,
                            GovernorateId = 14,
                            IsActive = true,
                            Name = "مركز فيصل",
                            Phone = "01000000092"
                        },
                        new
                        {
                            OfficeId = 93,
                            GovernorateId = 15,
                            IsActive = true,
                            Name = "مركز أسوان",
                            Phone = "01000000093"
                        },
                        new
                        {
                            OfficeId = 94,
                            GovernorateId = 15,
                            IsActive = true,
                            Name = "مركز إدفو",
                            Phone = "01000000094"
                        },
                        new
                        {
                            OfficeId = 95,
                            GovernorateId = 15,
                            IsActive = true,
                            Name = "مركز كوم أمبو",
                            Phone = "01000000095"
                        },
                        new
                        {
                            OfficeId = 96,
                            GovernorateId = 15,
                            IsActive = true,
                            Name = "مركز نصر النوبة",
                            Phone = "01000000096"
                        },
                        new
                        {
                            OfficeId = 97,
                            GovernorateId = 15,
                            IsActive = true,
                            Name = "مركز دراو",
                            Phone = "01000000097"
                        },
                        new
                        {
                            OfficeId = 98,
                            GovernorateId = 16,
                            IsActive = true,
                            Name = "مركز أسيوط",
                            Phone = "01000000098"
                        },
                        new
                        {
                            OfficeId = 99,
                            GovernorateId = 16,
                            IsActive = true,
                            Name = "مركز أبنوب",
                            Phone = "01000000099"
                        },
                        new
                        {
                            OfficeId = 100,
                            GovernorateId = 16,
                            IsActive = true,
                            Name = "مركز البداري",
                            Phone = "01000000100"
                        },
                        new
                        {
                            OfficeId = 101,
                            GovernorateId = 16,
                            IsActive = true,
                            Name = "مركز ديروط",
                            Phone = "01000000101"
                        },
                        new
                        {
                            OfficeId = 102,
                            GovernorateId = 16,
                            IsActive = true,
                            Name = "مركز القوصية",
                            Phone = "01000000102"
                        },
                        new
                        {
                            OfficeId = 103,
                            GovernorateId = 16,
                            IsActive = true,
                            Name = "مركز منفلوط",
                            Phone = "01000000103"
                        },
                        new
                        {
                            OfficeId = 104,
                            GovernorateId = 16,
                            IsActive = true,
                            Name = "مركز صدفا",
                            Phone = "01000000104"
                        },
                        new
                        {
                            OfficeId = 105,
                            GovernorateId = 16,
                            IsActive = true,
                            Name = "مركز الفتح",
                            Phone = "01000000105"
                        },
                        new
                        {
                            OfficeId = 106,
                            GovernorateId = 16,
                            IsActive = true,
                            Name = "مركز ساحل سليم",
                            Phone = "01000000106"
                        },
                        new
                        {
                            OfficeId = 107,
                            GovernorateId = 17,
                            IsActive = true,
                            Name = "مركز بني سويف",
                            Phone = "01000000107"
                        },
                        new
                        {
                            OfficeId = 108,
                            GovernorateId = 17,
                            IsActive = true,
                            Name = "مركز الفشن",
                            Phone = "01000000108"
                        },
                        new
                        {
                            OfficeId = 109,
                            GovernorateId = 17,
                            IsActive = true,
                            Name = "مركز ناصر",
                            Phone = "01000000109"
                        },
                        new
                        {
                            OfficeId = 110,
                            GovernorateId = 17,
                            IsActive = true,
                            Name = "مركز إهناسيا",
                            Phone = "01000000110"
                        },
                        new
                        {
                            OfficeId = 111,
                            GovernorateId = 17,
                            IsActive = true,
                            Name = "مركز ببا",
                            Phone = "01000000111"
                        },
                        new
                        {
                            OfficeId = 112,
                            GovernorateId = 17,
                            IsActive = true,
                            Name = "مركز سمسطا",
                            Phone = "01000000112"
                        },
                        new
                        {
                            OfficeId = 113,
                            GovernorateId = 18,
                            IsActive = true,
                            Name = "مركز بورسعيد",
                            Phone = "01000000113"
                        },
                        new
                        {
                            OfficeId = 114,
                            GovernorateId = 18,
                            IsActive = true,
                            Name = "مركز بورفؤاد",
                            Phone = "01000000114"
                        },
                        new
                        {
                            OfficeId = 115,
                            GovernorateId = 18,
                            IsActive = true,
                            Name = "مركز الزهور",
                            Phone = "01000000115"
                        },
                        new
                        {
                            OfficeId = 116,
                            GovernorateId = 19,
                            IsActive = true,
                            Name = "مركز دمياط",
                            Phone = "01000000116"
                        },
                        new
                        {
                            OfficeId = 117,
                            GovernorateId = 19,
                            IsActive = true,
                            Name = "مركز فارسكور",
                            Phone = "01000000117"
                        },
                        new
                        {
                            OfficeId = 118,
                            GovernorateId = 19,
                            IsActive = true,
                            Name = "مركز كفر سعد",
                            Phone = "01000000118"
                        },
                        new
                        {
                            OfficeId = 119,
                            GovernorateId = 19,
                            IsActive = true,
                            Name = "مركز الزرقا",
                            Phone = "01000000119"
                        },
                        new
                        {
                            OfficeId = 120,
                            GovernorateId = 20,
                            IsActive = true,
                            Name = "مركز الزقازيق",
                            Phone = "01000000120"
                        },
                        new
                        {
                            OfficeId = 121,
                            GovernorateId = 20,
                            IsActive = true,
                            Name = "مركز بلبيس",
                            Phone = "01000000121"
                        },
                        new
                        {
                            OfficeId = 122,
                            GovernorateId = 20,
                            IsActive = true,
                            Name = "مركز منيا القمح",
                            Phone = "01000000122"
                        },
                        new
                        {
                            OfficeId = 123,
                            GovernorateId = 20,
                            IsActive = true,
                            Name = "مركز أبو حماد",
                            Phone = "01000000123"
                        },
                        new
                        {
                            OfficeId = 124,
                            GovernorateId = 20,
                            IsActive = true,
                            Name = "مركز ديرب نجم",
                            Phone = "01000000124"
                        },
                        new
                        {
                            OfficeId = 125,
                            GovernorateId = 20,
                            IsActive = true,
                            Name = "مركز الحسينية",
                            Phone = "01000000125"
                        },
                        new
                        {
                            OfficeId = 126,
                            GovernorateId = 20,
                            IsActive = true,
                            Name = "مركز فاقوس",
                            Phone = "01000000126"
                        },
                        new
                        {
                            OfficeId = 127,
                            GovernorateId = 20,
                            IsActive = true,
                            Name = "مركز القنايات",
                            Phone = "01000000127"
                        },
                        new
                        {
                            OfficeId = 128,
                            GovernorateId = 20,
                            IsActive = true,
                            Name = "مركز كفر صقر",
                            Phone = "01000000128"
                        },
                        new
                        {
                            OfficeId = 129,
                            GovernorateId = 20,
                            IsActive = true,
                            Name = "مركز ههيا",
                            Phone = "01000000129"
                        },
                        new
                        {
                            OfficeId = 130,
                            GovernorateId = 20,
                            IsActive = true,
                            Name = "مركز العاشر من رمضان",
                            Phone = "01000000130"
                        },
                        new
                        {
                            OfficeId = 131,
                            GovernorateId = 21,
                            IsActive = true,
                            Name = "مركز شرم الشيخ",
                            Phone = "01000000131"
                        },
                        new
                        {
                            OfficeId = 132,
                            GovernorateId = 21,
                            IsActive = true,
                            Name = "مركز دهب",
                            Phone = "01000000132"
                        },
                        new
                        {
                            OfficeId = 133,
                            GovernorateId = 21,
                            IsActive = true,
                            Name = "مركز طور سيناء",
                            Phone = "01000000133"
                        },
                        new
                        {
                            OfficeId = 134,
                            GovernorateId = 21,
                            IsActive = true,
                            Name = "مركز أبو رديس",
                            Phone = "01000000134"
                        },
                        new
                        {
                            OfficeId = 135,
                            GovernorateId = 21,
                            IsActive = true,
                            Name = "مركز نويبع",
                            Phone = "01000000135"
                        },
                        new
                        {
                            OfficeId = 136,
                            GovernorateId = 22,
                            IsActive = true,
                            Name = "مركز كفر الشيخ",
                            Phone = "01000000136"
                        },
                        new
                        {
                            OfficeId = 137,
                            GovernorateId = 22,
                            IsActive = true,
                            Name = "مركز دسوق",
                            Phone = "01000000137"
                        },
                        new
                        {
                            OfficeId = 138,
                            GovernorateId = 22,
                            IsActive = true,
                            Name = "مركز فوة",
                            Phone = "01000000138"
                        },
                        new
                        {
                            OfficeId = 139,
                            GovernorateId = 22,
                            IsActive = true,
                            Name = "مركز بيلا",
                            Phone = "01000000139"
                        },
                        new
                        {
                            OfficeId = 140,
                            GovernorateId = 22,
                            IsActive = true,
                            Name = "مركز الرياض",
                            Phone = "01000000140"
                        },
                        new
                        {
                            OfficeId = 141,
                            GovernorateId = 22,
                            IsActive = true,
                            Name = "مركز مطوبس",
                            Phone = "01000000141"
                        },
                        new
                        {
                            OfficeId = 142,
                            GovernorateId = 22,
                            IsActive = true,
                            Name = "مركز سيدي سالم",
                            Phone = "01000000142"
                        },
                        new
                        {
                            OfficeId = 143,
                            GovernorateId = 22,
                            IsActive = true,
                            Name = "مركز الحامول",
                            Phone = "01000000143"
                        },
                        new
                        {
                            OfficeId = 144,
                            GovernorateId = 22,
                            IsActive = true,
                            Name = "مركز قلين",
                            Phone = "01000000144"
                        },
                        new
                        {
                            OfficeId = 145,
                            GovernorateId = 23,
                            IsActive = true,
                            Name = "مركز مطروح",
                            Phone = "01000000145"
                        },
                        new
                        {
                            OfficeId = 146,
                            GovernorateId = 23,
                            IsActive = true,
                            Name = "مركز سيدي براني",
                            Phone = "01000000146"
                        },
                        new
                        {
                            OfficeId = 147,
                            GovernorateId = 23,
                            IsActive = true,
                            Name = "مركز الضبعة",
                            Phone = "01000000147"
                        },
                        new
                        {
                            OfficeId = 148,
                            GovernorateId = 23,
                            IsActive = true,
                            Name = "مركز سلوم",
                            Phone = "01000000148"
                        },
                        new
                        {
                            OfficeId = 149,
                            GovernorateId = 23,
                            IsActive = true,
                            Name = "مركز السلوم",
                            Phone = "01000000149"
                        },
                        new
                        {
                            OfficeId = 150,
                            GovernorateId = 24,
                            IsActive = true,
                            Name = "مركز الأقصر",
                            Phone = "01000000150"
                        },
                        new
                        {
                            OfficeId = 151,
                            GovernorateId = 24,
                            IsActive = true,
                            Name = "مركز إسنا",
                            Phone = "01000000151"
                        },
                        new
                        {
                            OfficeId = 152,
                            GovernorateId = 24,
                            IsActive = true,
                            Name = "مركز أرمنت",
                            Phone = "01000000152"
                        },
                        new
                        {
                            OfficeId = 153,
                            GovernorateId = 25,
                            IsActive = true,
                            Name = "مركز قنا",
                            Phone = "01000000153"
                        },
                        new
                        {
                            OfficeId = 154,
                            GovernorateId = 25,
                            IsActive = true,
                            Name = "مركز نجع حمادي",
                            Phone = "01000000154"
                        },
                        new
                        {
                            OfficeId = 155,
                            GovernorateId = 25,
                            IsActive = true,
                            Name = "مركز قوص",
                            Phone = "01000000155"
                        },
                        new
                        {
                            OfficeId = 156,
                            GovernorateId = 25,
                            IsActive = true,
                            Name = "مركز دشنا",
                            Phone = "01000000156"
                        },
                        new
                        {
                            OfficeId = 157,
                            GovernorateId = 25,
                            IsActive = true,
                            Name = "مركز أبو تشت",
                            Phone = "01000000157"
                        },
                        new
                        {
                            OfficeId = 158,
                            GovernorateId = 25,
                            IsActive = true,
                            Name = "مركز فرشوط",
                            Phone = "01000000158"
                        },
                        new
                        {
                            OfficeId = 159,
                            GovernorateId = 25,
                            IsActive = true,
                            Name = "مركز نقادة",
                            Phone = "01000000159"
                        },
                        new
                        {
                            OfficeId = 160,
                            GovernorateId = 26,
                            IsActive = true,
                            Name = "مركز العريش",
                            Phone = "01000000160"
                        },
                        new
                        {
                            OfficeId = 161,
                            GovernorateId = 26,
                            IsActive = true,
                            Name = "مركز رفح",
                            Phone = "01000000161"
                        },
                        new
                        {
                            OfficeId = 162,
                            GovernorateId = 26,
                            IsActive = true,
                            Name = "مركز الشيخ زويد",
                            Phone = "01000000162"
                        },
                        new
                        {
                            OfficeId = 163,
                            GovernorateId = 26,
                            IsActive = true,
                            Name = "مركز بئر العبد",
                            Phone = "01000000163"
                        },
                        new
                        {
                            OfficeId = 164,
                            GovernorateId = 26,
                            IsActive = true,
                            Name = "مركز نخل",
                            Phone = "01000000164"
                        },
                        new
                        {
                            OfficeId = 165,
                            GovernorateId = 27,
                            IsActive = true,
                            Name = "مركز سوهاج",
                            Phone = "01000000165"
                        },
                        new
                        {
                            OfficeId = 166,
                            GovernorateId = 27,
                            IsActive = true,
                            Name = "مركز طهطا",
                            Phone = "01000000166"
                        },
                        new
                        {
                            OfficeId = 167,
                            GovernorateId = 27,
                            IsActive = true,
                            Name = "مركز جرجا",
                            Phone = "01000000167"
                        },
                        new
                        {
                            OfficeId = 168,
                            GovernorateId = 27,
                            IsActive = true,
                            Name = "مركز أخميم",
                            Phone = "01000000168"
                        },
                        new
                        {
                            OfficeId = 169,
                            GovernorateId = 27,
                            IsActive = true,
                            Name = "مركز البلينا",
                            Phone = "01000000169"
                        },
                        new
                        {
                            OfficeId = 170,
                            GovernorateId = 27,
                            IsActive = true,
                            Name = "مركز دار السلام",
                            Phone = "01000000170"
                        },
                        new
                        {
                            OfficeId = 171,
                            GovernorateId = 27,
                            IsActive = true,
                            Name = "مركز المراغة",
                            Phone = "01000000171"
                        },
                        new
                        {
                            OfficeId = 172,
                            GovernorateId = 27,
                            IsActive = true,
                            Name = "مركز المنشاة",
                            Phone = "01000000172"
                        },
                        new
                        {
                            OfficeId = 173,
                            GovernorateId = 27,
                            IsActive = true,
                            Name = "مركز ساقلتة",
                            Phone = "01000000173"
                        });
                });

            modelBuilder.Entity("Civil_Registration_System_Platform.Models.ServicesTypeHelper", b =>
                {
                    b.Property<int>("ServicesTypeEnum")
                        .HasColumnType("int");

                    b.Property<int>("ApplicationTypeEnum")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("DurationInDays")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("ServicesTypeEnum", "ApplicationTypeEnum");

                    b.ToTable("ServicesTypeHelpers");

                    b.HasData(
                        new
                        {
                            ServicesTypeEnum = 1,
                            ApplicationTypeEnum = 1,
                            Details = "الرقم القومي|اسم الأم الثلاثي",
                            DurationInDays = 0,
                            Price = 63
                        },
                        new
                        {
                            ServicesTypeEnum = 1,
                            ApplicationTypeEnum = 6,
                            Details = "إشعار ولادة من المستشفى|بطاقة ولي الأمر",
                            DurationInDays = 0,
                            Price = 0
                        },
                        new
                        {
                            ServicesTypeEnum = 2,
                            ApplicationTypeEnum = 1,
                            Details = "تقرير طبي|إشعار الوفاة من المستشفى",
                            DurationInDays = 1,
                            Price = 63
                        },
                        new
                        {
                            ServicesTypeEnum = 3,
                            ApplicationTypeEnum = 1,
                            Details = "بيانات الزوج والزوجة (ثلاثي-رباعي)|تاريخ الزواج",
                            DurationInDays = 1,
                            Price = 63
                        },
                        new
                        {
                            ServicesTypeEnum = 4,
                            ApplicationTypeEnum = 1,
                            Details = "بيانات الزوج والزوجة|تاريخ الطلاق",
                            DurationInDays = 1,
                            Price = 63
                        },
                        new
                        {
                            ServicesTypeEnum = 5,
                            ApplicationTypeEnum = 1,
                            Details = "شهادة ميلاد مميكنة|عدد 2 صورة شخصية|قيد عائلي أو إثبات إقامة",
                            DurationInDays = 7,
                            Price = 75
                        },
                        new
                        {
                            ServicesTypeEnum = 5,
                            ApplicationTypeEnum = 2,
                            Details = "البطاقة القديمة|عدد 2 صورة شخصية",
                            DurationInDays = 7,
                            Price = 75
                        },
                        new
                        {
                            ServicesTypeEnum = 5,
                            ApplicationTypeEnum = 3,
                            Details = "محضر فقدان|عدد 2 صورة شخصية",
                            DurationInDays = 7,
                            Price = 315
                        },
                        new
                        {
                            ServicesTypeEnum = 5,
                            ApplicationTypeEnum = 4,
                            Details = "البطاقة التالفة|عدد 2 صورة شخصية",
                            DurationInDays = 7,
                            Price = 265
                        },
                        new
                        {
                            ServicesTypeEnum = 6,
                            ApplicationTypeEnum = 1,
                            Details = "بطاقة قومي سارية|عدد 4 صور شخصية|شهادة موقف التجنيد (للذكور)",
                            DurationInDays = 7,
                            Price = 500
                        },
                        new
                        {
                            ServicesTypeEnum = 6,
                            ApplicationTypeEnum = 2,
                            Details = "الجواز القديم|بطاقة قومي سارية|عدد 4 صور شخصية",
                            DurationInDays = 7,
                            Price = 500
                        },
                        new
                        {
                            ServicesTypeEnum = 6,
                            ApplicationTypeEnum = 3,
                            Details = "محضر فقدان|بطاقة قومي سارية|عدد 4 صور شخصية|شهادة موقف التجنيد (للذكور)",
                            DurationInDays = 7,
                            Price = 600
                        },
                        new
                        {
                            ServicesTypeEnum = 6,
                            ApplicationTypeEnum = 4,
                            Details = "الجواز التالف|بطاقة قومي سارية",
                            DurationInDays = 7,
                            Price = 500
                        },
                        new
                        {
                            ServicesTypeEnum = 8,
                            ApplicationTypeEnum = 1,
                            Details = "الرقم القومي|اسم رب الأسرة",
                            DurationInDays = 1,
                            Price = 63
                        },
                        new
                        {
                            ServicesTypeEnum = 9,
                            ApplicationTypeEnum = 1,
                            Details = "الرقم القومي",
                            DurationInDays = 1,
                            Price = 63
                        },
                        new
                        {
                            ServicesTypeEnum = 10,
                            ApplicationTypeEnum = 1,
                            Details = "بطاقة قومي + مؤهل دراسي|عدد 2 صورة شخصية|إثبات إقامة",
                            DurationInDays = 14,
                            Price = 1140
                        },
                        new
                        {
                            ServicesTypeEnum = 10,
                            ApplicationTypeEnum = 2,
                            Details = "الرخصة القديمة|شهادة براءة ذمة",
                            DurationInDays = 14,
                            Price = 1105
                        },
                        new
                        {
                            ServicesTypeEnum = 10,
                            ApplicationTypeEnum = 3,
                            Details = "بطاقة قومي|محضر فقدان|شهادة براءة ذمة",
                            DurationInDays = 14,
                            Price = 265
                        },
                        new
                        {
                            ServicesTypeEnum = 10,
                            ApplicationTypeEnum = 4,
                            Details = "بطاقة قومي|الرخصة التالفة|شهادة براءة ذمة",
                            DurationInDays = 14,
                            Price = 215
                        });
                });

            modelBuilder.Entity("Civil_Registration_System_Platform.Models.TimelineEntry", b =>
                {
                    b.Property<int>("TimelineEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TimelineEntryId"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PerformedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("UserAccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TimelineEntryId");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("PerformedById");

                    b.ToTable("TimelineEntries");
                });

            modelBuilder.Entity("Civil_Registration_System_Platform.Models.UserAccount", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("CardImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("EGPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int?>("GovernorateId")
                        .HasColumnType("int");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRejected")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ManageOfficeId")
                        .HasColumnType("int");

                    b.Property<int>("MaritalStatus")
                        .HasColumnType("int");

                    b.Property<string>("NationalID")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("OfficeId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RejectionMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("GovernorateId");

                    b.HasIndex("ManageOfficeId");

                    b.HasIndex("NationalID")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("OfficeId");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasFilter("[UserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            CardImagePath = "default.png",
                            ConcurrencyStamp = "f13a3b84-e88b-4dd0-b75d-1964737a49bb",
                            CreatedAt = new DateOnly(2026, 5, 5),
                            EGPhoneNumber = "01000000000",
                            Email = "superadmin@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Super Admin",
                            Gender = 1,
                            IsConfirmed = true,
                            IsRejected = false,
                            LockoutEnabled = false,
                            MaritalStatus = 1,
                            NationalID = "12345678901234",
                            NormalizedEmail = "SUPERADMIN@GMAIL.COM",
                            NormalizedUserName = "SUPERADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEOzJeOGCPuekLOZZuOQE66ZQXtsAvTepo4fe+p5b4XNDj0JYg5vYjriRK+jdor/2EA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "efed3c4a-84aa-4616-9302-ba4898560034",
                            TwoFactorEnabled = false,
                            UserName = "superadmin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "SuperAdmin",
                            NormalizedName = "SUPERADMIN"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "3",
                            Name = "Employee",
                            NormalizedName = "EMPLOYEE"
                        },
                        new
                        {
                            Id = "4",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "1",
                            RoleId = "1"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Civil_Registration_System_Platform.Models.Application", b =>
                {
                    b.HasOne("Civil_Registration_System_Platform.Models.Office", "Office")
                        .WithMany("Applications")
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Civil_Registration_System_Platform.Models.UserAccount", "ReviewedUserAccount")
                        .WithMany("ApplicationsReviewed")
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Civil_Registration_System_Platform.Models.UserAccount", "UserAccount")
                        .WithMany("ApplicationsApply")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Office");

                    b.Navigation("ReviewedUserAccount");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Civil_Registration_System_Platform.Models.ApplicationDocuments", b =>
                {
                    b.HasOne("Civil_Registration_System_Platform.Models.Application", "Application")
                        .WithMany("ApplicationDocuments")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Civil_Registration_System_Platform.Models.Appointment", b =>
                {
                    b.HasOne("Civil_Registration_System_Platform.Models.Application", "Application")
                        .WithMany("Appointments")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Civil_Registration_System_Platform.Models.UserAccount", "ScheduledBy")
                        .WithMany("Appointments")
                        .HasForeignKey("ScheduledById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("ScheduledBy");
                });

            modelBuilder.Entity("Civil_Registration_System_Platform.Models.Office", b =>
                {
                    b.HasOne("Civil_Registration_System_Platform.Models.Governorate", "Governorate")
                        .WithMany("Offices")
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Governorate");
                });

            modelBuilder.Entity("Civil_Registration_System_Platform.Models.TimelineEntry", b =>
                {
                    b.HasOne("Civil_Registration_System_Platform.Models.Application", "Application")
                        .WithMany("TimelineEntries")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Civil_Registration_System_Platform.Models.UserAccount", "PerformedBy")
                        .WithMany("TimelineEntries")
                        .HasForeignKey("PerformedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("PerformedBy");
                });

            modelBuilder.Entity("Civil_Registration_System_Platform.Models.UserAccount", b =>
                {
                    b.HasOne("Civil_Registration_System_Platform.Models.Governorate", "Governorate")
                        .WithMany("UserAccounts")
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Civil_Registration_System_Platform.Models.Office", "ManageOffice")
                        .WithMany("ManageUserAccounts")
                        .HasForeignKey("ManageOfficeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Civil_Registration_System_Platform.Models.Office", "Office")
                        .WithMany("UserAccounts")
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Governorate");

                    b.Navigation("ManageOffice");

                    b.Navigation("Office");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Civil_Registration_System_Platform.Models.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Civil_Registration_System_Platform.Models.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Civil_Registration_System_Platform.Models.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Civil_Registration_System_Platform.Models.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Civil_Registration_System_Platform.Models.Application", b =>
                {
                    b.Navigation("ApplicationDocuments");

                    b.Navigation("Appointments");

                    b.Navigation("TimelineEntries");
                });

            modelBuilder.Entity("Civil_Registration_System_Platform.Models.Governorate", b =>
                {
                    b.Navigation("Offices");

                    b.Navigation("UserAccounts");
                });

            modelBuilder.Entity("Civil_Registration_System_Platform.Models.Office", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("ManageUserAccounts");

                    b.Navigation("UserAccounts");
                });

            modelBuilder.Entity("Civil_Registration_System_Platform.Models.UserAccount", b =>
                {
                    b.Navigation("ApplicationsApply");

                    b.Navigation("ApplicationsReviewed");

                    b.Navigation("Appointments");

                    b.Navigation("TimelineEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
